### ISSUE TITLE
Running type inference failed

### ISSUE THREAD

**Issue by bdemick** [trailofbits/BTIGhidra#42]
I threw `BTIGhidra` up against a stripped `vmlinux` ELF with the intent to test it against the debug version with `BTIEval` and it failed after about 80 minutes. Backtrace is below for posterity, but it doesn't provide much insight.

### System Information
Platform: macOS 14.3
Ghidra 11.0.1
Java: Corretto-17.0.6.10.1
BTIGhidra version: 0.0.5

### Backtrace
```
Running type inference failed
java.lang.RuntimeException: Running type inference failed
at binary_type_inference.BinaryTypeInference.getCtypes(BinaryTypeInference.java:339)
at binary_type_inference.BinaryTypeInference.run(BinaryTypeInference.java:479)
at binary_type_inference.TypeAnalyzer.added(TypeAnalyzer.java:213)
at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:186)
at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:686)
at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:786)
at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:665)
at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:630)
at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:103)
at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:334)
at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by 2over12** [comment]
Thanks for taking a look. Currently we do a whole program fixpoint for pointer analysis in cwe-checker. I suspect that is quite the long running task and then potentially hit an issue in the type inference component. The performance of pre-analysis is something we are tracking and looking into solutions for. 

In the meantime there are a couple of options you can use. 
![Screenshot 2024-02-07 at 5 20 18 PM](https://github.com/trailofbits/BTIGhidra/assets/19430893/b734c832-8499-42b5-b1ee-f1b77486d796)

Entry points list, takes a ";" delimited set of entry points which will limit the analysis to some target set of functions that are transitively called by the entry-point. The debug dir option will save all inputs and logs to tmp which will provide all the artifacts required to repro the inference run if you want to debug this further or provide a zip so that we can look into it

**Comment by ggrieco-tob** [comment]
I got the same error when running this extension on a small binary in my Arch Linux (x64) (which finished immediately with the same error)

**Comment by 2over12** [comment]
@ggrieco-tob without a test binary it will be fairly difficult to debug the issues (or the artifacts available when saving to the debug dir). In the meantime I am opening a PR to provide more informative error messages related to unsupported arches and adding m1 releases

**Comment by 2over12** [comment]
I've added a new release with m1 binaries and more informative error messages for a situation where the original binary is not found https://github.com/trailofbits/BTIGhidra/releases/tag/btighidra-v0.0.6. Hopefully this helps

**Comment by unknown321** [comment]
Same issue while analyzing ARM, EABI5 library on Linux x64

Platform: Debian 12
Ghidra 11.0.1
Java: Corretto-17.0.9.8.1-linux-x64
BTIGhidra version: 0.0.6

File: [libc-2.23.so.zip](https://github.com/trailofbits/BTIGhidra/files/14251472/libc-2.23.so.zip)

<details>

```
Running type inference failed 
java.lang.RuntimeException: Running type inference failed 
	at binary_type_inference.BinaryTypeInference.getCtypes(BinaryTypeInference.java:336)
	at binary_type_inference.BinaryTypeInference.run(BinaryTypeInference.java:476)
	at binary_type_inference.TypeAnalyzer.added(TypeAnalyzer.java:213)
	at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:186)
	at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:686)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:786)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:665)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:630)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:103)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:334)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
</details>

**Comment by bdemick** [comment]
Tried again with the updated version and it ended up dying with the same exception, but this time after about 9 hours. Definitely reached another phase of analysis, because `/tmp` filled up with analysis artifacts. I don't see a more specific log there, and it looks like the last temp file was created roughly 6 hours before it eventually crashed.

I'm going to retry with a single entry point as well. If you want to try to repro, any stripped x86-64 Linux kernel binary should probably do the trick.

**Comment by alexdetrano** [comment]
I am also getting the same error on my 2019 Intel MacBook Pro. I used the same libc02.23.so.zip file above (https://github.com/trailofbits/BTIGhidra/files/14251472/libc-2.23.so.zip)

Platform: Macbook Pro (2019), Intel CPU
Ghidra 11.0.0
Java: OpenJDK 20.0.1
BTIGhidra version: 0.0.6

```
(These messages are also written to the application log file)

Running type inference failed 
java.lang.RuntimeException: Running type inference failed 
	at binary_type_inference.BinaryTypeInference.getCtypes(BinaryTypeInference.java:336)
	at binary_type_inference.BinaryTypeInference.run(BinaryTypeInference.java:476)
	at binary_type_inference.TypeAnalyzer.added(TypeAnalyzer.java:213)
	at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:186)
	at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:686)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:786)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:665)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:630)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:103)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:334)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by zeredy879** [comment]
> I got the same error when running this extension on a small binary in my Arch Linux (x64) (which finished immediately with the same error)

same here, hope new release could help

**Comment by tiandiyixian** [comment]
this problem can be soloved by  update  glibc  to >=2.34
