### ISSUE TITLE
Type Inference - Cannot read the array length because "array" is null

### ISSUE THREAD

**Issue by vhoual** [trailofbits/BTIGhidra#44]
```
Cannot read the array length because "array" is null
java.lang.NullPointerException: Cannot read the array length because "array" is null
	at java.base/java.util.Arrays.stream(Arrays.java:5428)
	at binary_type_inference.PreservedFunctionList.createFromExternSection(PreservedFunctionList.java:36)
	at binary_type_inference.TypeAnalyzer.added(TypeAnalyzer.java:194)
	at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:186)
	at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:686)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:786)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:665)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:630)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:103)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:334)
	at java.base/java.lang.Thread.run(Thread.java:840)

---------------------------------------------------
Build Date: 2024-Jan-30 2221 UTC
Ghidra Version: 11.0.1
Java Home: /usr/lib/jvm/java-17-openjdk
JVM Version: N/A 17.0.10
OS: Linux 6.7.4-arch1-1 amd64
```

I'm running BTIGhidra on a windows DLL and i got this error, i've tried to setup an entry point list but it end up the same.

**Comment by 2over12** [comment]
Fix here https://github.com/trailofbits/BTIGhidra/pull/45

**Comment by 2over12** [comment]
I've cut a new release with this change https://github.com/trailofbits/BTIGhidra/releases/tag/btighidra-v0.0.6
